services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    ports:
      - "5000:5000"
    environment:
      - DEFAULT_SOURCE=en
      - DEFAULT_TARGET=nb
    volumes:
      - libre-data:/data

  nllb:
    build:
      context: ./nllb
    environment:
      - NLLB_MODEL=facebook/nllb-200-3.3B
      - NLLB_DEVICE=cuda
      # Smoother GPU usage
      - NLLB_BATCH_SIZE=16
      - NLLB_MAX_NEW_TOKENS=256
      - NLLB_NUM_BEAMS=1
      # Cap CPU threads used by libs inside the container
      - OMP_NUM_THREADS=2
      - MKL_NUM_THREADS=2
      - TORCH_NUM_THREADS=2
    volumes:
      - nllb-cache:/models/.cache/huggingface
    ports:
      - "6100:6100"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  app:
    build:
      context: ./app
    ports:
      - "8080:8080"
    depends_on:
      - libretranslate
      - nllb
    environment:
      - DEFAULT_SOURCE=en
      - DEFAULT_TARGET=nb
      - DEFAULT_ENGINE=auto
      - NLLB_ENDPOINT=http://nllb:6100
      - LIBRE_ENDPOINT=http://libretranslate:5000

volumes:
  libre-data:
  nllb-cache:
